version: '3'
services:
  db:
    container_name: 'product_db'
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'root'
    entrypoint:
      sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS ProductDB; GRANT ALL PRIVILEGES ON ProductDB.* TO '\''root'\''@'\''%'\''; ' > /docker-entrypoint-initdb.d/init.sql;
        echo 'CREATE DATABASE IF NOT EXISTS ProductTestDB; GRANT ALL PRIVILEGES ON ProductTestDB.* TO '\''root'\''@'\''%'\''; ' >> /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password"
    ports:
        - '4306:3306'
    volumes:
      - ./data/db:/data/db

  cache:
    container_name: 'product_redis'
    image: redis:latest
    ports:
        - '6379:6379'

  api:
    container_name: product-list-api
    image: product-list-api
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: ProductDB
      DB_PORT: 3306
      REDIS_HOST: cache
      NODE_ENV: development
      API_BASE_ENDPOINT: 'http://localhost:3000'
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app 
    depends_on:
      - db
      - cache

