version: '3'
services:
  db:
    container_name: 'product_db'
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'product-api-db'
      MYSQL_PASSWORD: 'root'
    ports:
        - '4306:3306'
    volumes:
      - ./data/db:/data/db

  cache:
    container_name: 'product_redis'
    image: redis:latest
    ports:
        - '6379:6379'

  api:
    container_name: product-list-api
    image: product-list-api
    environment:
      DB_HOST: db
      DB_USERNAME: 'root'
      DB_PASSWORD: 'root'
      DB_NAME: 'product-api-db'
      REDIS_HOST: cache
      NODE_ENV: development
      API_BASE_ENDPOINT: 'http://localhost:3000'
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app 
    depends_on:
      - db
      - cache

