version: '3'
services:
  db:
    container_name: 'product_db'
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    entrypoint:
      sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS $DB_NAME; GRANT ALL PRIVILEGES ON $DB_NAME.* TO '\''$DB_USERNAME'\''@'\''%'\''; ' > /docker-entrypoint-initdb.d/init.sql;
        echo 'CREATE DATABASE IF NOT EXISTS $TEST_DB_NAME; GRANT ALL PRIVILEGES ON $TEST_DB_NAME.* TO '\''$DB_USERNAME'\''@'\''%'\''; ' >> /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password"
    ports:
        - '4306:3306'
    volumes:
      - ./data/db:/data/db

  cache:
    container_name: 'product_redis'
    image: redis:latest
    ports:
        - '6379:6379'

  api:
    container_name: product-list-api
    image: product-list-api
    environment:
      DB_HOST: db
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_PORT: 3306
      REDIS_HOST: cache
      NODE_ENV: "${NODE_ENV}"
      API_BASE_ENDPOINT: "${API_BASE_ENDPOINT}"
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app 
    depends_on:
      - db
      - cache

